const LOGIN = 'LOGIN'
const LOGOUT = 'LOGOUT'
const START_SEEDING = 'START_SEEDING'
const FINISHED_SEEDING = 'FINISH_SEEDING'

module.exports = {
  LOGIN,
  LOGOUT,
  START_SEEDING,
  FINISHED_SEEDING
}
