const LOGIN = 'LOGIN'
const LOGOUT = 'LOGOUT'
const UPDATE = 'UPDATE'
const START_SEEDING = 'START_SEEDING'
const FINISHED_SEEDING = 'FINISH_SEEDING'

module.exports = {
  LOGIN,
  LOGOUT,
  UPDATE,
  START_SEEDING,
  FINISHED_SEEDING
}
